### ISSUE TITLE
cannot build backend django project

### ISSUE THREAD

**Issue by SHoar** [RobertTownley/ink#1]
I am going through the Getting Started Guide and am able to get to the point where the backend `docker-compose build` reports `Successfully tagged <my-site-name>-backend:latest.

The next step is to run `docker-compose exec backend django-admin startproject backend . `

When I run this command from either at the project root or from within <my-site-name>/backend, docker gives the error:

'ERROR: No container found for backend_1`

I'm wondering if it hasn't installed the dependencies for django-admin? here was my docker compose  build stdoutput:

```➜  try-ink-cms docker-compose build
db uses an image, skipping
Building backend
Step 1/12 : FROM python:3
 ---> efdecc2e377a
Step 2/12 : ENV PYTHONUNBUFFERED 1
 ---> Using cache
 ---> 778fcf77715b
Step 3/12 : RUN mkdir /backend
 ---> Using cache
 ---> 15f606d4d12b
Step 4/12 : EXPOSE 8000
 ---> Using cache
 ---> 9d7fb7660c2e
Step 5/12 : WORKDIR /backend
 ---> Using cache
 ---> b0295dcf74e9
Step 6/12 : RUN pip install --upgrade pip
 ---> Using cache
 ---> c0dd672e5b18
Step 7/12 : RUN pip install poetry
 ---> Using cache
 ---> 7e9a7b547234
Step 8/12 : RUN poetry config virtualenvs.create false
 ---> Using cache
 ---> b6806680edf8
Step 9/12 : COPY pyproject.toml .
 ---> Using cache
 ---> e7ab15a7d314
Step 10/12 : COPY poetry.lock .
 ---> Using cache
 ---> bb0b88c5c4c3
Step 11/12 : RUN poetry install
 ---> Using cache
 ---> c50e09840c92
Step 12/12 : CMD /backend/entrypoint.sh
 ---> Using cache
 ---> 8b2f083ad424
Successfully built 8b2f083ad424
Successfully tagged try-ink-cms_backend:latest```

**Comment by RobertTownley** [comment]
Thanks @SHoar I really appreciate you filing the issue, and helping to debug the setup instructions!

I think the issue is that an earlier version of the setup instructions already had a containerized version of the project running at the step you referenced. In the newer version, there's no running container, so docker's `exec` command has no running container to execute the command within.

I think the solution is to switch the step to instead use `docker-compose run` which spins up a container for the purpose of running that command. I've added a few steps to the instructions that change `exec` to `run`, and add a step to remove build artifacts later in the process (`run` leaves some running containers). My hunch is that should resolve your issue, but let me know if it doesn't work for you.

**Comment by SHoar** [comment]
That did the trick! I was able to complete the Getting started guide.  It took a little bit to download the postgres docker image, but it was smooth sailing after that.
